name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Java
        run: sudo apt update && sudo apt install openjdk-17-jdk

      - name: Set JAVA_HOME to Java 17
        run: |
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify Java 17
          distribution: 'temurin'

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME is set to: $JAVA_HOME"
          echo "Path to java: $(which java)"
          echo "Java installation directory: $(dirname $(dirname $(readlink -f $(which java))))"

      - name: Set JAVA_HOME to correct directory
        run: |
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x springBoot/task-manager-backend/gradlew

      - name: Clean Gradle cache
        run: ./gradlew clean
        
      - name: Build with Gradle
        run: cd springBoot/task-manager-backend && ./gradlew build --no-configuration-cache --stacktrace

